### ISSUE TITLE
v1 protocol for communication with BYO KV service

### ISSUE THREAD

**Issue by fhoering** [privacysandbox/bidding-auction-servers#21]
For compatibility reasons with Chrome and on-device auctions the bidding & auction service should support the v1 protocol with BYO KV service. Is this the case ? 
How one can configure this service ? Normally it is an https endpoint like https://mykvservice.com/getvalues (below it is specified as  "dns:///..")

Existing terraform example config is here:
https://github.com/privacysandbox/bidding-auction-servers/blob/main/production/deploy/aws/terraform/environment/demo/buyer/buyer.tf#L30

```
  tee_kv_server_exists  = false
  tee_kv_server_domain  = "kv-${local.buyer_operator}-${local.environment}-appmesh-virtual-service.${local.buyer_root_domain}"
  tee_kv_server_address = "dns:///${local.tee_kv_server_domain}:50051"
```

**Comment by akundla-google** [comment]
B&A supports BYOS KV for Protected Audience only. You'd set the address for this for the buyer on Line 89, `BUYER_KV_SERVER_ADDR`, https://github.com/privacysandbox/bidding-auction-servers/blob/722e1542c262dddc3aaf41be7b6c159a38cefd0a/production/deploy/aws/terraform/environment/demo/buyer/buyer.tf#L89

**Comment by fhoering** [comment]
OK. Thanks. My use case is protected audience.

So to sum it up:
- `tee_kv_server_domain`  is the TEE KV service
- `BUYER_KV_SERVER_ADDR` is the buyer BYO KV service  which receives queries with the v1 protocol (the same way as chrome sends requests)
- both can coexist at the same time.                         

Can you confirm ?

**Comment by peiwenhu** [comment]
At this moment the tee_kv_server_domain is for the TEE KV service used by Protected App Signals. It is not used for Protected Audience.

However, we did in the past seek feedback on BYOS+TKV [coexisting](https://github.com/WICG/protected-auction-services-discussion/blob/main/meetings/2024-07-03-PAS-call-minutes.md) so that--although not possible now--is an idea we would be happy to see interests.

**Comment by fhoering** [comment]
OK. It is fine for now as we already have PA BYO KV server up and running and we will see at a later stage of testing for the TEE KV server.

**Comment by akundla-google** [comment]
Closing as resolved, reopen if necessary
