### ISSUE TITLE
Release 4.1.0: PCR0 mismatch in AWS build

### ISSUE THREAD

**Issue by ccharnay67** [privacysandbox/bidding-auction-servers#24]
Hello,

We have been building buyer services on AWS instances, but we do not observe the same PCR0 as in the [release notes](https://github.com/privacysandbox/bidding-auction-servers/releases).

For buyer_frontend_service_non_prod in release-4.1, built with `production/packaging/build_and_test_all_in_docker --service-path buyer_frontend_service --with-ami us-east-1 --platform aws --instance aws --build-flavor non_prod --no-tests --no-precommit`, we should have
`{"PCR0":"5f2ad634d6f69c98206609fbd3798e1f329e0088e759889742ebd81ca7bae12d26a1cd4d01a7d91fa29a4c6fa611e925"}`, but we get the following in dist/aws/buyer_frontend_service_non_prod.json
`{
  "Measurements": {
    "HashAlgorithm": "Sha384 { ... }",
    "PCR0": "6d51f7ade17249e671548f0d01cffad8bd5dc5a1a760fca0d3e0be04a5cb2606e0754a42d4ac6998db93704f23e718bb",
    "PCR1": "0343b056cd8485ca7890ddd833476d78460aed2aa161548e4e26bedf321726696257d623e8805f3f605946b3d8b0c6aa",
    "PCR2": "c85fb101f84e99712e68735bbe2fe5395e2c41a5c2ad6629da04b5eabc15a3d1ef1ee4692a1f9d2074188fa07b7e6a1e"
  }
}`

Do you have any explanations for the mismatch? What could affect its value?

We built on an Amazon Linux t2.xlarge instance, with 4 vCPUs and 16 GB of RAM.

**Comment by ccharnay67** [comment]
Same observation for bidding_service, expected PCR0 was `{"PCR0":"8be9d0e07539933a6a2be67202b80da85e0e9dd83ff92beb3c441ac31c9db1b39cbd00546e7fc347bfe23983c4dd8834"}`, but we obtained
```
cat dist/aws/bidding_service_non_prod.json
{
  "Measurements": {
    "HashAlgorithm": "Sha384 { ... }",
    "PCR0": "ae9165eaf706a13d699eee690e7582a4c504b453598d0c0dfcbaf7b7145612581c2482bc1252654ba69fd786d7f471ea",
    "PCR1": "0343b056cd8485ca7890ddd833476d78460aed2aa161548e4e26bedf321726696257d623e8805f3f605946b3d8b0c6aa",
    "PCR2": "c1c58446349f82105e8ba94dd5a7ceb6e2bf10cc9ca550718c24a9f539636af1802bb2f9def1e11a4c0880c51472e0d2"
  }
}
```

**Comment by webmihir** [comment]
Thank you for reporting this issue Clément. Our oncall is investigating and will have an update shortly.

**Comment by salmanmlk** [comment]
Hello! We were able to reproduce the problem and believe this is due to a dependency changing in our build system. We our working on pinning that dependency  and will create a new release afterwards.  We will update here again once the issue is resolved.

**Comment by ccharnay67** [comment]
Hello!

I just tested again on the new release-4.2 branch, and I confirm the PCR0 I get when building buyer_frontend_service_non_prod and bidding_service_non_prod on an AWS instance match the ones you give in the release notes.

Closing the issue, thanks for looking into this!
