### ISSUE TITLE
[Question] Customizing Bidding Server API Config - Adding Gender Field

### ISSUE THREAD

**Issue by HankyStyle** [privacysandbox/bidding-auction-servers#8]
Hi everyone,

I am currently working with the Bidding Server API in our project, and I have a question about customizing the configuration.

I am interested in adding an additional field for "gender" in the API config, and I'm wondering if anyone has experience doing something similar. Could someone kindly guide me on how I can achieve this or point me in the right direction?

Here's a brief overview of what I'm trying to accomplish:

**Objective:** Add a "gender" field to the Bidding Server API config.
**Question:** Is it possible to customize the config, and if so, what steps should I follow?

Any insights, code snippets, or documentation references would be greatly appreciated. Thank you in advance for your assistance!

[Reference for API Input](https://github.com/privacysandbox/bidding-auction-servers/blob/main/api/bidding_auction_servers.proto)

**Comment by arunnair236** [comment]
Thanks for your question, @HankyStyle. I am not sure what the exact use case is but there are a couple options available to you.
a) If you are doing retargeting, then it is possible for you to add any signal (including gender) in [user_bidding_signals](https://github.com/privacysandbox/bidding-auction-servers/blob/main/api/bidding_auction_servers.proto#L131).
b) If you are using Protected App Signals then these signals can be made available as part of [app install signals](https://github.com/privacysandbox/bidding-auction-servers/blob/main/api/bidding_auction_servers.proto#L87C9-L87C28) using the APIs described [here](https://developer.android.com/design-for-safety/privacy-sandbox/guides/protected-audience/protected-app-signals#buyer-signals) 

In both these cases these signals would be available in generateBid() for bidding on relevant Ads.

**Comment by HankyStyle** [comment]
Hi! @arunnair236,
my main use case is in case a, where I am doing retargeting.
I appreciate the suggestions you provided.

Thank you very much for your response!
